Intersection reflection
pvlkhn/msu-python-project pull request #10
Opened 2021-04-09 21:50 UTC by NikitaD617

2021-04-09 22:12 UTC, aiosadchy requested changes

2021-04-09 22:12 UTC, aiosadchy commented on client/model.py
> +        distance = np.linalg.norm((ball_center[0] - x, ball_center[1] - y))
Не уверен, что для этих трёх операций нужен целый numpy

2021-04-09 22:12 UTC, aiosadchy commented on client/controller.py
> +            ball.reflect()
Такое решение имеет проблему: если на следующий кадр после отражения от платформы мяч снова окажется на пересечении с платформой (например, если платформа передвинулась), он снова отразится от неё в обратную сторону
Предлагаю примерно такое решение: отражать мяч только в том случае, если он движется в сторону платформы
Скажем, для нижней платформы проверять, что `ball.direction[1] > 0`, для верхней -- `< 0`

2021-04-09 22:12 UTC, aiosadchy commented on client/controller.py
> +            ball.reflect()
Ещё, если мы хотим поддержать поворот платформы, стоит в reflect передавать её угол и считать более сложное пересечение (сфера с наклонённым прямоугольником), но пока достаточно и того, что есть, я думаю

2021-04-09 22:12 UTC, aiosadchy commented on client/controller.py
> +        ball.move()  # TODO: handle intersection
todo стоит убрать, раз ты его сделал)

2021-04-11 10:40 UTC, NikitaD617 commented on client/model.py
> +        distance = np.linalg.norm((ball_center[0] - x, ball_center[1] - y))
Напишу тогда кастомные функции?

2021-04-11 11:37 UTC, NikitaD617 commented on client/model.py
> +        distance = np.linalg.norm((ball_center[0] - x, ball_center[1] - y))
Написал кастомные функции, вынес в utils.py

2021-04-11 11:37 UTC, NikitaD617 commented on client/controller.py
> +            ball.reflect()
Добавил проверку направления движения

2021-04-11 11:38 UTC, NikitaD617 commented on client/controller.py
> +        ball.move()  # TODO: handle intersection
Убрал

2021-04-11 16:20 UTC, aiosadchy approved these changes
Кажется, должно работать

2021-04-11 19:01 UTC, pvlkhn approved these changes

2021-04-11 19:01 UTC, pvlkhn commented on client/model.py
> +    def get_direction(self):
вроде эти методы не используются вне класса, но и не мешают

2021-04-12 19:16 UTC, merged